[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = "debuginfo"

[[bin]]
name = "day01"
path = "src/day01/main.rs"
